// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Perspektif.API.Data;

#nullable disable

namespace Perspektif.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515185356_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Perspektif.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "🍽️",
                            Name = "Yemek & İçecek"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "🏛️",
                            Name = "Kültür & Tarih"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "🏨",
                            Name = "Konaklama"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "🚇",
                            Name = "Ulaşım"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "🌿",
                            Name = "Doğa & Manzara"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "🌃",
                            Name = "Gece Hayatı"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "🛍️",
                            Name = "Alışveriş"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "🔒",
                            Name = "Güvenlik"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "🗣️",
                            Name = "Dil & İletişim"
                        },
                        new
                        {
                            Id = 10,
                            Icon = "💰",
                            Name = "Para & Bütçe"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "☀️",
                            Name = "Hava & İklim"
                        },
                        new
                        {
                            Id = 12,
                            Icon = "🎯",
                            Name = "Eğlence & Aktivite"
                        },
                        new
                        {
                            Id = 13,
                            Icon = "🏥",
                            Name = "Sağlık & Hastane"
                        },
                        new
                        {
                            Id = 14,
                            Icon = "📋",
                            Name = "Vizyon & Pratik Bilgi"
                        },
                        new
                        {
                            Id = 15,
                            Icon = "💡",
                            Name = "Diğer"
                        });
                });

            modelBuilder.Entity("Perspektif.API.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Perspektif.API.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("User1Id")
                        .HasColumnType("integer");

                    b.Property<int>("User2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt")
                        .HasDatabaseName("IX_Conversations_LastMessageAt");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Conversations_User1_User2");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Perspektif.API.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlagEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TR",
                            FlagEmoji = "🇹🇷",
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DE",
                            FlagEmoji = "🇩🇪",
                            Name = "Almanya"
                        },
                        new
                        {
                            Id = 3,
                            Code = "FR",
                            FlagEmoji = "🇫🇷",
                            Name = "Fransa"
                        },
                        new
                        {
                            Id = 4,
                            Code = "GB",
                            FlagEmoji = "🇬🇧",
                            Name = "İngiltere"
                        },
                        new
                        {
                            Id = 5,
                            Code = "IT",
                            FlagEmoji = "🇮🇹",
                            Name = "İtalya"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ES",
                            FlagEmoji = "🇪🇸",
                            Name = "İspanya"
                        },
                        new
                        {
                            Id = 7,
                            Code = "NL",
                            FlagEmoji = "🇳🇱",
                            Name = "Hollanda"
                        },
                        new
                        {
                            Id = 8,
                            Code = "GR",
                            FlagEmoji = "🇬🇷",
                            Name = "Yunanistan"
                        },
                        new
                        {
                            Id = 9,
                            Code = "PT",
                            FlagEmoji = "🇵🇹",
                            Name = "Portekiz"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AT",
                            FlagEmoji = "🇦🇹",
                            Name = "Avusturya"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CH",
                            FlagEmoji = "🇨🇭",
                            Name = "İsviçre"
                        },
                        new
                        {
                            Id = 12,
                            Code = "BE",
                            FlagEmoji = "🇧🇪",
                            Name = "Belçika"
                        },
                        new
                        {
                            Id = 13,
                            Code = "SE",
                            FlagEmoji = "🇸🇪",
                            Name = "İsveç"
                        },
                        new
                        {
                            Id = 14,
                            Code = "NO",
                            FlagEmoji = "🇳🇴",
                            Name = "Norveç"
                        },
                        new
                        {
                            Id = 15,
                            Code = "DK",
                            FlagEmoji = "🇩🇰",
                            Name = "Danimarka"
                        },
                        new
                        {
                            Id = 16,
                            Code = "PL",
                            FlagEmoji = "🇵🇱",
                            Name = "Polonya"
                        },
                        new
                        {
                            Id = 17,
                            Code = "CZ",
                            FlagEmoji = "🇨🇿",
                            Name = "Çekya"
                        },
                        new
                        {
                            Id = 18,
                            Code = "HU",
                            FlagEmoji = "🇭🇺",
                            Name = "Macaristan"
                        },
                        new
                        {
                            Id = 19,
                            Code = "HR",
                            FlagEmoji = "🇭🇷",
                            Name = "Hırvatistan"
                        },
                        new
                        {
                            Id = 20,
                            Code = "RS",
                            FlagEmoji = "🇷🇸",
                            Name = "Sırbistan"
                        },
                        new
                        {
                            Id = 21,
                            Code = "RO",
                            FlagEmoji = "🇷🇴",
                            Name = "Romanya"
                        },
                        new
                        {
                            Id = 22,
                            Code = "RU",
                            FlagEmoji = "🇷🇺",
                            Name = "Rusya"
                        },
                        new
                        {
                            Id = 23,
                            Code = "FI",
                            FlagEmoji = "🇫🇮",
                            Name = "Finlandiya"
                        },
                        new
                        {
                            Id = 24,
                            Code = "JP",
                            FlagEmoji = "🇯🇵",
                            Name = "Japonya"
                        },
                        new
                        {
                            Id = 25,
                            Code = "KR",
                            FlagEmoji = "🇰🇷",
                            Name = "Güney Kore"
                        },
                        new
                        {
                            Id = 26,
                            Code = "CN",
                            FlagEmoji = "🇨🇳",
                            Name = "Çin"
                        },
                        new
                        {
                            Id = 27,
                            Code = "IN",
                            FlagEmoji = "🇮🇳",
                            Name = "Hindistan"
                        },
                        new
                        {
                            Id = 28,
                            Code = "TH",
                            FlagEmoji = "🇹🇭",
                            Name = "Tayland"
                        },
                        new
                        {
                            Id = 29,
                            Code = "ID",
                            FlagEmoji = "🇮🇩",
                            Name = "Endonezya"
                        },
                        new
                        {
                            Id = 30,
                            Code = "SG",
                            FlagEmoji = "🇸🇬",
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = 31,
                            Code = "MY",
                            FlagEmoji = "🇲🇾",
                            Name = "Malezya"
                        },
                        new
                        {
                            Id = 32,
                            Code = "VN",
                            FlagEmoji = "🇻🇳",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 33,
                            Code = "PH",
                            FlagEmoji = "🇵🇭",
                            Name = "Filipinler"
                        },
                        new
                        {
                            Id = 34,
                            Code = "TW",
                            FlagEmoji = "🇹🇼",
                            Name = "Tayvan"
                        },
                        new
                        {
                            Id = 35,
                            Code = "HK",
                            FlagEmoji = "🇭🇰",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 36,
                            Code = "NP",
                            FlagEmoji = "🇳🇵",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 37,
                            Code = "LK",
                            FlagEmoji = "🇱🇰",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 38,
                            Code = "AE",
                            FlagEmoji = "🇦🇪",
                            Name = "Dubai (BAE)"
                        },
                        new
                        {
                            Id = 39,
                            Code = "SA",
                            FlagEmoji = "🇸🇦",
                            Name = "Suudi Arabistan"
                        },
                        new
                        {
                            Id = 40,
                            Code = "QA",
                            FlagEmoji = "🇶🇦",
                            Name = "Katar"
                        },
                        new
                        {
                            Id = 41,
                            Code = "IL",
                            FlagEmoji = "🇮🇱",
                            Name = "İsrail"
                        },
                        new
                        {
                            Id = 42,
                            Code = "EG",
                            FlagEmoji = "🇪🇬",
                            Name = "Mısır"
                        },
                        new
                        {
                            Id = 43,
                            Code = "MA",
                            FlagEmoji = "🇲🇦",
                            Name = "Fas"
                        },
                        new
                        {
                            Id = 44,
                            Code = "ZA",
                            FlagEmoji = "🇿🇦",
                            Name = "Güney Afrika"
                        },
                        new
                        {
                            Id = 45,
                            Code = "KE",
                            FlagEmoji = "🇰🇪",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 46,
                            Code = "TN",
                            FlagEmoji = "🇹🇳",
                            Name = "Tunus"
                        },
                        new
                        {
                            Id = 47,
                            Code = "US",
                            FlagEmoji = "🇺🇸",
                            Name = "ABD"
                        },
                        new
                        {
                            Id = 48,
                            Code = "CA",
                            FlagEmoji = "🇨🇦",
                            Name = "Kanada"
                        },
                        new
                        {
                            Id = 49,
                            Code = "MX",
                            FlagEmoji = "🇲🇽",
                            Name = "Meksika"
                        },
                        new
                        {
                            Id = 50,
                            Code = "BR",
                            FlagEmoji = "🇧🇷",
                            Name = "Brezilya"
                        },
                        new
                        {
                            Id = 51,
                            Code = "AR",
                            FlagEmoji = "🇦🇷",
                            Name = "Arjantin"
                        },
                        new
                        {
                            Id = 52,
                            Code = "CO",
                            FlagEmoji = "🇨🇴",
                            Name = "Kolombiya"
                        },
                        new
                        {
                            Id = 53,
                            Code = "PE",
                            FlagEmoji = "🇵🇪",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 54,
                            Code = "CU",
                            FlagEmoji = "🇨🇺",
                            Name = "Küba"
                        },
                        new
                        {
                            Id = 55,
                            Code = "AU",
                            FlagEmoji = "🇦🇺",
                            Name = "Avustralya"
                        },
                        new
                        {
                            Id = 56,
                            Code = "NZ",
                            FlagEmoji = "🇳🇿",
                            Name = "Yeni Zelanda"
                        },
                        new
                        {
                            Id = 57,
                            Code = "GE",
                            FlagEmoji = "🇬🇪",
                            Name = "Gürcistan"
                        },
                        new
                        {
                            Id = 58,
                            Code = "AZ",
                            FlagEmoji = "🇦🇿",
                            Name = "Azerbaycan"
                        },
                        new
                        {
                            Id = 59,
                            Code = "AL",
                            FlagEmoji = "🇦🇱",
                            Name = "Arnavutluk"
                        },
                        new
                        {
                            Id = 60,
                            Code = "ME",
                            FlagEmoji = "🇲🇪",
                            Name = "Karadağ"
                        });
                });

            modelBuilder.Entity("Perspektif.API.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BudgetLevel")
                        .HasColumnType("text");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("IX_Experiences_CountryId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Experiences_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Experiences_UserId");

                    b.HasIndex("CountryId", "UserId")
                        .HasDatabaseName("IX_Experiences_Country_User");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Perspektif.API.Models.ExperienceLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ExperienceId", "UserId")
                        .IsUnique();

                    b.ToTable("ExperienceLikes");
                });

            modelBuilder.Entity("Perspektif.API.Models.ExperiencePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudinaryUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.ToTable("ExperiencePhotos");
                });

            modelBuilder.Entity("Perspektif.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeletedByUser1")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeletedByUser2")
                        .HasColumnType("boolean");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_Messages_ConversationId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Messages_CreatedAt");

                    b.HasIndex("IsDeletedByUser1")
                        .HasDatabaseName("IX_Messages_IsDeletedByUser1");

                    b.HasIndex("IsDeletedByUser2")
                        .HasDatabaseName("IX_Messages_IsDeletedByUser2");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Perspektif.API.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlagEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TR",
                            FlagEmoji = "🇹🇷",
                            Name = "Türk"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DE",
                            FlagEmoji = "🇩🇪",
                            Name = "Alman"
                        },
                        new
                        {
                            Id = 3,
                            Code = "FR",
                            FlagEmoji = "🇫🇷",
                            Name = "Fransız"
                        },
                        new
                        {
                            Id = 4,
                            Code = "GB",
                            FlagEmoji = "🇬🇧",
                            Name = "İngiliz"
                        },
                        new
                        {
                            Id = 5,
                            Code = "US",
                            FlagEmoji = "🇺🇸",
                            Name = "Amerikalı"
                        },
                        new
                        {
                            Id = 6,
                            Code = "JP",
                            FlagEmoji = "🇯🇵",
                            Name = "Japon"
                        },
                        new
                        {
                            Id = 7,
                            Code = "IT",
                            FlagEmoji = "🇮🇹",
                            Name = "İtalyan"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ES",
                            FlagEmoji = "🇪🇸",
                            Name = "İspanyol"
                        },
                        new
                        {
                            Id = 9,
                            Code = "RU",
                            FlagEmoji = "🇷🇺",
                            Name = "Rus"
                        },
                        new
                        {
                            Id = 10,
                            Code = "CN",
                            FlagEmoji = "🇨🇳",
                            Name = "Çinli"
                        },
                        new
                        {
                            Id = 11,
                            Code = "NL",
                            FlagEmoji = "🇳🇱",
                            Name = "Hollandalı"
                        },
                        new
                        {
                            Id = 12,
                            Code = "GR",
                            FlagEmoji = "🇬🇷",
                            Name = "Yunan"
                        },
                        new
                        {
                            Id = 13,
                            Code = "PT",
                            FlagEmoji = "🇵🇹",
                            Name = "Portekizli"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AT",
                            FlagEmoji = "🇦🇹",
                            Name = "Avusturyalı"
                        },
                        new
                        {
                            Id = 15,
                            Code = "CH",
                            FlagEmoji = "🇨🇭",
                            Name = "İsviçreli"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BE",
                            FlagEmoji = "🇧🇪",
                            Name = "Belçikalı"
                        },
                        new
                        {
                            Id = 17,
                            Code = "SE",
                            FlagEmoji = "🇸🇪",
                            Name = "İsveçli"
                        },
                        new
                        {
                            Id = 18,
                            Code = "NO",
                            FlagEmoji = "🇳🇴",
                            Name = "Norveçli"
                        },
                        new
                        {
                            Id = 19,
                            Code = "DK",
                            FlagEmoji = "🇩🇰",
                            Name = "Danimarkalı"
                        },
                        new
                        {
                            Id = 20,
                            Code = "PL",
                            FlagEmoji = "🇵🇱",
                            Name = "Polonyalı"
                        },
                        new
                        {
                            Id = 21,
                            Code = "CZ",
                            FlagEmoji = "🇨🇿",
                            Name = "Çekli"
                        },
                        new
                        {
                            Id = 22,
                            Code = "HU",
                            FlagEmoji = "🇭🇺",
                            Name = "Macar"
                        },
                        new
                        {
                            Id = 23,
                            Code = "HR",
                            FlagEmoji = "🇭🇷",
                            Name = "Hırvat"
                        },
                        new
                        {
                            Id = 24,
                            Code = "RO",
                            FlagEmoji = "🇷🇴",
                            Name = "Rumen"
                        },
                        new
                        {
                            Id = 25,
                            Code = "RS",
                            FlagEmoji = "🇷🇸",
                            Name = "Sırp"
                        },
                        new
                        {
                            Id = 26,
                            Code = "FI",
                            FlagEmoji = "🇫🇮",
                            Name = "Fin"
                        },
                        new
                        {
                            Id = 27,
                            Code = "KR",
                            FlagEmoji = "🇰🇷",
                            Name = "Güney Koreli"
                        },
                        new
                        {
                            Id = 28,
                            Code = "IN",
                            FlagEmoji = "🇮🇳",
                            Name = "Hintli"
                        },
                        new
                        {
                            Id = 29,
                            Code = "TW",
                            FlagEmoji = "🇹🇼",
                            Name = "Tayvanlı"
                        },
                        new
                        {
                            Id = 30,
                            Code = "TH",
                            FlagEmoji = "🇹🇭",
                            Name = "Taylandlı"
                        },
                        new
                        {
                            Id = 31,
                            Code = "ID",
                            FlagEmoji = "🇮🇩",
                            Name = "Endonezyal"
                        },
                        new
                        {
                            Id = 32,
                            Code = "SG",
                            FlagEmoji = "🇸🇬",
                            Name = "Singapurlu"
                        },
                        new
                        {
                            Id = 33,
                            Code = "MY",
                            FlagEmoji = "🇲🇾",
                            Name = "Malezyalı"
                        },
                        new
                        {
                            Id = 34,
                            Code = "VN",
                            FlagEmoji = "🇻🇳",
                            Name = "Vietnamlı"
                        },
                        new
                        {
                            Id = 35,
                            Code = "PH",
                            FlagEmoji = "🇵🇭",
                            Name = "Filipinli"
                        },
                        new
                        {
                            Id = 36,
                            Code = "NP",
                            FlagEmoji = "🇳🇵",
                            Name = "Nepalli"
                        },
                        new
                        {
                            Id = 37,
                            Code = "LK",
                            FlagEmoji = "🇱🇰",
                            Name = "Sri Lankalı"
                        },
                        new
                        {
                            Id = 38,
                            Code = "AE",
                            FlagEmoji = "🇦🇪",
                            Name = "Emiratli"
                        },
                        new
                        {
                            Id = 39,
                            Code = "SA",
                            FlagEmoji = "🇸🇦",
                            Name = "Suudi"
                        },
                        new
                        {
                            Id = 40,
                            Code = "QA",
                            FlagEmoji = "🇶🇦",
                            Name = "Katarlı"
                        },
                        new
                        {
                            Id = 41,
                            Code = "IL",
                            FlagEmoji = "🇮🇱",
                            Name = "İsrailli"
                        },
                        new
                        {
                            Id = 42,
                            Code = "EG",
                            FlagEmoji = "🇪🇬",
                            Name = "Mısırlı"
                        },
                        new
                        {
                            Id = 43,
                            Code = "MA",
                            FlagEmoji = "🇲🇦",
                            Name = "Faslı"
                        },
                        new
                        {
                            Id = 44,
                            Code = "ZA",
                            FlagEmoji = "🇿🇦",
                            Name = "Güney Afrikalı"
                        },
                        new
                        {
                            Id = 45,
                            Code = "KE",
                            FlagEmoji = "🇰🇪",
                            Name = "Kenyalı"
                        },
                        new
                        {
                            Id = 46,
                            Code = "TN",
                            FlagEmoji = "🇹🇳",
                            Name = "Tunuslu"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CA",
                            FlagEmoji = "🇨🇦",
                            Name = "Kanadalı"
                        },
                        new
                        {
                            Id = 48,
                            Code = "MX",
                            FlagEmoji = "🇲🇽",
                            Name = "Meksikalı"
                        },
                        new
                        {
                            Id = 49,
                            Code = "BR",
                            FlagEmoji = "🇧🇷",
                            Name = "Brezilyalı"
                        },
                        new
                        {
                            Id = 50,
                            Code = "AR",
                            FlagEmoji = "🇦🇷",
                            Name = "Arjantinli"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CO",
                            FlagEmoji = "🇨🇴",
                            Name = "Kolombiyalı"
                        },
                        new
                        {
                            Id = 52,
                            Code = "PE",
                            FlagEmoji = "🇵🇪",
                            Name = "Perulu"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CU",
                            FlagEmoji = "🇨🇺",
                            Name = "Kübalı"
                        },
                        new
                        {
                            Id = 54,
                            Code = "AU",
                            FlagEmoji = "🇦🇺",
                            Name = "Avustralyalı"
                        },
                        new
                        {
                            Id = 55,
                            Code = "NZ",
                            FlagEmoji = "🇳🇿",
                            Name = "Yeni Zelandalı"
                        },
                        new
                        {
                            Id = 56,
                            Code = "GE",
                            FlagEmoji = "🇬🇪",
                            Name = "Gürcü"
                        },
                        new
                        {
                            Id = 57,
                            Code = "AZ",
                            FlagEmoji = "🇦🇿",
                            Name = "Azerbaycanlı"
                        },
                        new
                        {
                            Id = 58,
                            Code = "AL",
                            FlagEmoji = "🇦🇱",
                            Name = "Arnavut"
                        },
                        new
                        {
                            Id = 59,
                            Code = "ME",
                            FlagEmoji = "🇲🇪",
                            Name = "Karadağlı"
                        },
                        new
                        {
                            Id = 60,
                            Code = "HK",
                            FlagEmoji = "🇭🇰",
                            Name = "Hong Konglu"
                        });
                });

            modelBuilder.Entity("Perspektif.API.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Perspektif.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NationalityId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NationalityId")
                        .HasDatabaseName("IX_Users_NationalityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Perspektif.API.Models.Comment", b =>
                {
                    b.HasOne("Perspektif.API.Models.Experience", "Experience")
                        .WithMany("Comments")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Perspektif.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Perspektif.API.Models.Conversation", b =>
                {
                    b.HasOne("Perspektif.API.Models.User", "User1")
                        .WithMany("ConversationsAsUser1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Perspektif.API.Models.User", "User2")
                        .WithMany("ConversationsAsUser2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Perspektif.API.Models.Experience", b =>
                {
                    b.HasOne("Perspektif.API.Models.Category", "Category")
                        .WithMany("Experiences")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Perspektif.API.Models.Country", "Country")
                        .WithMany("Experiences")
                        .HasForeignKey("CountryId");

                    b.HasOne("Perspektif.API.Models.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Perspektif.API.Models.ExperienceLike", b =>
                {
                    b.HasOne("Perspektif.API.Models.Experience", "Experience")
                        .WithMany("Likes")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Perspektif.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Perspektif.API.Models.ExperiencePhoto", b =>
                {
                    b.HasOne("Perspektif.API.Models.Experience", "Experience")
                        .WithMany("Photos")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Perspektif.API.Models.Message", b =>
                {
                    b.HasOne("Perspektif.API.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Perspektif.API.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Perspektif.API.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Perspektif.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Perspektif.API.Models.User", b =>
                {
                    b.HasOne("Perspektif.API.Models.Nationality", "Nationality")
                        .WithMany("Users")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Perspektif.API.Models.Category", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("Perspektif.API.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Perspektif.API.Models.Country", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("Perspektif.API.Models.Experience", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Perspektif.API.Models.Nationality", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Perspektif.API.Models.User", b =>
                {
                    b.Navigation("ConversationsAsUser1");

                    b.Navigation("ConversationsAsUser2");

                    b.Navigation("Experiences");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
