/**
 * Statik şehir listesi — mobile/perspektif/src/services/cities.ts'tan kopya.
 * 60 ülke için tipik turistik şehir/bölge isimleri.
 * Backend'de değil, frontend'de tutuluyor (kullanıcıya hızlı autocomplete için).
 */
export const CITIES: Record<string, string[]> = {
  Türkiye: ['İstanbul','Ankara','İzmir','Antalya','Bursa','Trabzon','Kapadokya','Bodrum','Fethiye','Pamukkale','Alanya','Marmaris'],
  Almanya: ['Berlin','Münih','Hamburg','Frankfurt','Köln','Düsseldorf','Dresden','Heidelberg','Stuttgart','Nürnberg'],
  Fransa: ['Paris','Marsilya','Lyon','Nice','Bordeaux','Strasbourg','Toulouse','Nantes','Cannes','Mont Saint-Michel'],
  İngiltere: ['Londra','Manchester','Birmingham','Edinburgh','Liverpool','Bristol','Leeds','Glasgow','Oxford','Cambridge'],
  İtalya: ['Roma','Milano','Venedik','Floransa','Napoli','Bologna','Torino','Sicilya','Amalfi','Cinque Terre'],
  İspanya: ['Madrid','Barselona','Sevilla','Valencia','Granada','Bilbao','Malaga','Toledo','San Sebastián','Ibiza'],
  Hollanda: ['Amsterdam','Rotterdam','Lahey','Utrecht','Eindhoven','Delft','Haarlem'],
  Yunanistan: ['Atina','Selanik','Santorini','Mykonos','Rodos','Kreta','Korfu','Zakynthos'],
  Portekiz: ['Lizbon','Porto','Faro','Sintra','Coimbra','Braga','Madeira','Azorlar'],
  Avusturya: ['Viyana','Salzburg','İnnsbruck','Graz','Linz','Hallstatt'],
  İsviçre: ['Zürih','Cenevre','Bern','Lozan','Basel','Luzern','İnterlaken','Zermatt'],
  Belçika: ['Brüksel','Bruges','Gent','Anvers','Lüttich'],
  İsveç: ['Stockholm','Göteborg','Malmö','Uppsala','Kiruna'],
  Norveç: ['Oslo','Bergen','Tromsø','Stavanger','Ålesund'],
  Danimarka: ['Kopenhag','Aarhus','Odense','Aalborg'],
  Polonya: ['Varşova','Krakow','Wrocław','Gdańsk','Poznań','Zakopane'],
  Çekya: ['Prag','Brno','Ostrava','Český Krumlov'],
  Macaristan: ['Budapeşte','Debrecen','Pécs','Eger'],
  Hırvatistan: ['Zagreb','Dubrovnik','Split','Pula','Zadar','Hvar'],
  Romanya: ['Bükreş','Cluj-Napoca','Timişoara','Braşov','Sibiu'],
  Sırbistan: ['Belgrad','Novi Sad','Niş'],
  Rusya: ['Moskova','St. Petersburg','Kazan','Soçi','Vladivostok'],
  Finlandiya: ['Helsinki','Rovaniemi','Tampere','Turku'],
  Japonya: ['Tokyo','Osaka','Kyoto','Hiroshima','Nagoya','Sapporo','Fukuoka','Nara','Yokohama'],
  'Güney Kore': ['Seul','Busan','İncheon','Jeju','Daegu','Gyeongju'],
  Çin: ['Pekin','Şangay','Guangzhou','Şenzhen','Hangzhou','Chengdu','Xian','Guilin'],
  Hindistan: ['Mumbai','Delhi','Bangalore','Goa','Jaipur','Kolkata','Agra','Varanasi','Kerala'],
  Tayland: ['Bangkok','Phuket','Chiang Mai','Pattaya','Koh Samui','Koh Phi Phi','Koh Tao'],
  Endonezya: ['Bali','Jakarta','Yogyakarta','Lombok','Komodo','Gili Adaları'],
  Singapur: ['Singapur','Sentosa'],
  Malezya: ['Kuala Lumpur','Penang','Langkawi','Malacca','Kota Kinabalu'],
  Vietnam: ['Ho Chi Minh','Hanoi','Hoi An','Da Nang','Nha Trang','Ha Long'],
  Filipinler: ['Manila','Cebu','Boracay','Palawan','Siargao'],
  Tayvan: ['Taipei','Tainan','Kaohsiung','Taroko'],
  'Hong Kong': ['Hong Kong Adası','Kowloon','Lantau'],
  Nepal: ['Katmandu','Pokhara','Everest Bölgesi','Chitwan'],
  'Sri Lanka': ['Colombo','Kandy','Galle','Sigiriya','Ella'],
  'Dubai (BAE)': ['Dubai','Abu Dabi','Şarjah','Ras Al Khaimah'],
  'Suudi Arabistan': ['Riyad','Cidde','Mekke','Medine','AlUla'],
  Katar: ['Doha','Lusail'],
  İsrail: ['Tel Aviv','Kudüs','Hayfa','Eilat','Nazaret'],
  Mısır: ['Kahire','Şarm El Şeyh','Hurgada','Luksor','İskenderiye','Aswan'],
  Fas: ['Marakeş','Kazablanka','Fes','Tanca','Rabat','Şefşaven'],
  'Güney Afrika': ['Johannesburg','Cape Town','Durban','Pretoria','Garden Route'],
  Kenya: ['Nairobi','Masai Mara','Mombasa','Amboseli'],
  Tunus: ['Tunus','Hammamet','Sfaks','Carthage'],
  ABD: ['New York','Los Angeles','Chicago','Miami','San Francisco','Las Vegas','Washington D.C.','Boston','Seattle','New Orleans','Hawaii','Grand Canyon'],
  Kanada: ['Toronto','Vancouver','Montreal','Calgary','Ottawa','Quebec','Whistler','Banff'],
  Meksika: ['Mexico City','Cancún','Guadalajara','Tulum','Playa del Carmen','Oaxaca','San Cristóbal'],
  Brezilya: ['São Paulo','Rio de Janeiro','Salvador','Florianópolis','Manaus','Foz do Iguaçu'],
  Arjantin: ['Buenos Aires','Mendoza','Córdoba','Bariloche','El Calafate'],
  Kolombiya: ['Bogota','Cartagena','Medellín','Santa Marta'],
  Peru: ['Lima','Cusco','Machu Picchu','Arequipa','İkitos'],
  Küba: ['Havana','Varadero','Trinidad','Cienfuegos'],
  Avustralya: ['Sydney','Melbourne','Brisbane','Perth','Adelaide','Gold Coast','Cairns','Uluru'],
  'Yeni Zelanda': ['Auckland','Queenstown','Wellington','Christchurch','Rotorua','Milford Sound'],
  Gürcistan: ['Tiflis','Batum','Kazbegi','Kutaisi','Svaneti'],
  Azerbaycan: ['Bakü','Guba','Şeki','Qabala'],
  Arnavutluk: ['Tiran','Sarandë','Berat','Shkodër'],
  Karadağ: ['Kotor','Budva','Podgorica','Bar','Ulcinj'],
}
